bin/cygport.in (cygautoreconf): Don't force path of autoreconf.

diff --git a/bin/cygport.in b/bin/cygport.in
--- a/bin/cygport.in
+++ b/bin/cygport.in
@@ -1043,7 +1043,7 @@ cygautoreconf() {
 		fi
 	fi
 
-	/usr/bin/autoreconf --force -i --verbose || error "autoreconf failed"
+	autoreconf --force -i --verbose || error "autoreconf failed"
 
 	for d in . ${ac_subdirs}
 	do
