Ignore errors in nested source-ing of cygport
This avoids immediately terminating on calling the 'exit' built-in after
any error in the source-ing (e.g. raised by free code in an inherited
cygclass), which causes a silent exit now we that suppress stderr from
that nested source-ing.

We do this by writing "( stuff-which-may-exit ) || true".

You might think that the extra subshell is not needed.  I certainly did,
(because the rules for the 'errexit' mode (which the subshell inherits)
are that non-final commands in || lists don't cause an exit if they
fail).  I was baffled for a long time as to why it's needed until I
realized that the 'exit' built-in causes the shell to exit, even when
it succeeds.

The '|| true' ensures that the substitution does not have a non-zero
exit status, which is an error in the top-level shell.

Fixes: aa665473aa7d ("Send informational messages to stderr")

diff --git a/bin/cygport.in b/bin/cygport.in
--- a/bin/cygport.in
+++ b/bin/cygport.in
@@ -431,7 +431,10 @@ do
     n=0
     while (( n < ${#ARCHES[*]} ))
     do
-        read -r < <(declare ARCH=${ARCHES[$n]}; declare ARCH_${ARCH}=1; source ${top}/${cygportfile} 2>/dev/null; eval echo "\$${VAR}")
+        # the '\n' at the end ensures that if the source-ing fails, the process
+        # substitution still outputs something, so read has some input and
+        # doesn't fail on seeing an end-of-file
+        read -r < <( (declare ARCH=${ARCHES[$n]}; declare ARCH_${ARCH}=1; source ${top}/${cygportfile} 2>/dev/null ; eval echo "\$${VAR}}" ) || echo "\n" )
         VALUE[$n]=${REPLY}
         if (( n > 0 ))
         then
@@ -447,7 +450,7 @@ unset n VALUE ARCHES VAR
 
 # probe if the cygport sets ARCH - if it does, set ARCHES to that value,
 # otherwise set it to the default value "all".
-PROBE_ARCH=$(unset ARCH; source ${top}/${cygportfile} 2>/dev/null; echo "${ARCH}")
+PROBE_ARCH=$( (unset ARCH; source ${top}/${cygportfile} 2>/dev/null ; echo "${ARCH}") || true )
 if [ -z "${PROBE_ARCH}" ]
 then
 	declare -r ARCHES="all"
